name: MSPR_Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev


permissions: write-all

jobs:
  build:
    runs-on: openjdk-21
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test -Dmaven.test.skip=true

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          name: arosaje.jar
          path: ./target
