name: MSPR_Pipeline

on:
  push:
    branches:
      - main
      - dev
      - Init-pipeline
  pull_request:
    branches:
      - main
      - dev


permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: arosaje-jar
          path: target/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: arosaje-jar
          path: target
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: false # Set to true and configure Docker Hub credentials to push
          tags: maaawox/arosaje:latest # Replace 'user' with your Docker Hub username or organization
