name: MSPR_Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - dev


permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven and Analyze with SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar:sonar -Dsonar.projectKey=YourProjectKey -Dsonar.organization=YourOrganization -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}


      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v2
        with:
          name: arosaje-jar
          path: target/*.jar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Test with Maven
        run: mvn -B test --file pom.xml -Dspring.profiles.active=test

  docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JAR Artifact
        uses: actions/download-artifact@v2
        with:
          name: arosaje-jar
          path: target
      - name: Build and push Docker image
        run: docker build -t ghcr.io/matthieuderoir/arosaje/arosaje-backend:latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ghcr.io/matthieuderoir/arosaje/arosaje-backend:latest


